# 应用服务 WEB 访问端口
server:
  port: 8081

# spring 设置
spring:
  application:
    name: self-cookbook
mybatis:
  type-aliases-package: wang.zehui.selfcookbookjava.entity
  mapper-locations: "classpath:mappers/*xml"

